### ISSUE TITLE
Error: urlparse

### ISSUE THREAD

**Issue by cuevas1208** [pycontribs/django-alexa#32]
I followed the instructions from the read me file:
I installed it using: 
$ pip install django-alexa

In your django settings.py I added the following:

INSTALLED_APPS = [
    'django_alexa',
    ...
]

In your django urls.py I  added the following:
urlpatterns = [
    url(r'^', include('django_alexa.urls')),
    ...
]

I set this environment variables to configure the validation needs:
ALEXA_APP_ID_DEFAULT="My amazon id app"
ALEXA_APP_ID_OTHER=""
ALEXA_REQUEST_VERIFICATON=True # Enables/Disable request verification

and then I got this error:
```
(root) ubuntu@ip-172-31-2-119:~/rockford/examples/myproject$ python manage.py runserver 0:8001
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f195ee54d90>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/apps.py", line 9, in ready
    self.module.autodiscover()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/__init__.py", line 8, in autodiscover
    autodiscover_modules('alexa')
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/ubuntu/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/alexa.py", line 2, in <module>
    from .api import intent, ResponseBuilder
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/api/__init__.py", line 1, in <module>
    from django_alexa.internal import intent, ResponseBuilder  # NOQA
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/internal/__init__.py", line 4, in <module>
    from .validation import validate_reponse_limit, validate_alexa_request, validate_char_limit, validate_app_ids, ALEXA_APP_IDS  # flake8: noqa
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/django_alexa/internal/validation.py", line 10, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```

**Comment by cuevas1208** [comment]
nevermind, I was using the release version. The latest version is working fine.

**Comment by lingster** [comment]
Hi, have you tried including 'rest_framework' in your settings.py/INSTALLED_APPS config?
